### ISSUE TITLE
Avalonia XPlatform Support

### ISSUE THREAD

**Issue by mvegaca** [AvaloniaCommunity/MessageBox.Avalonia#126]
Hi!

I'm creating an application using Avalonia.XPlat template for .NET 7 (MacOS, Windows, iOS, Android).

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/5556784/223401346-058387d5-b515-4098-a042-2145d50b7d51.png">

When I run this code in iOS or Android execution I got this error.

`
{System.NotSupportedException: Specified method is not supported.
   at Avalonia.Android.WindowingPlatformStub.CreateWindow() in /_/src/Android/Avalonia.Android/Stubs.cs:line 9
   at Avalonia.Controls.Platform.PlatformManager.CreateWindow() in /_/src/Avalonia.Controls/Platform/PlatformManager.cs:line 31
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 219
   at MessageBox.Avalonia.Views.BaseWindow..ctor()
   at MessageBox.Avalonia.Views.MsBoxStandardWindow..ctor()
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(MessageBoxStandardParams params)
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(String title, String text, ButtonEnum enum, Icon icon, WindowStartupLocation windowStartupLocation)
   at Longoboard.UI.Services.NotificationsService.ShowNotification(INotification notification) in /Users/mvega/dev/LongoMatch/longoboard/Longoboard/Longoboard.UI/Services/NotificationsService.cs:line 115}
	base: {System.SystemException}
`

I'm not sure if I forgot to add something or if it's because this SDK isn't available for running Avalonia on iOS and Android.

I'm using Avalonia version 11.0.0-preview5 that contains the TopLevel API's that allows to get the window object from iOS or Android execution.

Thank you very much in advance!
Martin

**Comment by CreateLab** [comment]
Sorry, this project will no support xplat for now, it'may be done only with community support
Main problem -> in IOS or android u cant open additional window
Fix -> use DialogHost.Avalonia
