### ISSUE TITLE
Does not work on Avalonia 11.0.0-preview7

### ISSUE THREAD

**Issue by IhateTrains** [AvaloniaCommunity/MessageBox.Avalonia#136]
```
System.MissingMethodException: Method not found: 'Void Avalonia.StyledElement.set_Classes(Avalonia.Controls.Classes)'.
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulate(IServiceProvider, MsBoxCustomWindow)
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulateTrampoline(MsBoxCustomWindow)
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxCustomWindow..ctor()
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxCustomWindow(MessageBoxCustomParams params)
   ```

**Comment by IhateTrains** [comment]
Works with MessageBox.Avalonia version 2.3.1-prev7.0.
