### ISSUE TITLE
Doesn't work on Avalonia 11 RC1

### ISSUE THREAD

**Issue by IhateTrains** [AvaloniaCommunity/MessageBox.Avalonia#140]
```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void Avalonia.Styling.StyleBase.Add(Avalonia.Styling.ISetter)'.
  Source=MessageBox.Avalonia
  StackTrace:
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulate(IServiceProvider , MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulateTrampoline(MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxCustomWindow..ctor()
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxCustomWindow(MessageBoxCustomParams params)
   at Fronter.ViewModels.MainWindowViewModel.<CheckForUpdates>d__70.MoveNext() in D:\GitHub\IhateTrains\Fronter.NET\Fronter.NET\ViewModels\MainWindowViewModel.cs:line 247

```

**Comment by BullyWiiPlaza** [comment]
It seems like I'm running into the same issue: https://stackoverflow.com/questions/76543774

**Comment by CreateLab** [comment]
> It seems like I'm running into the same issue: https://stackoverflow.com/questions/76543774

Sry, dont read so. and miss here, use our telegram channels for fast communication

**Comment by CreateLab** [comment]
What version do u use, as i understand u use old version, which doesnt work with rc1, use rc1 version with rc1

**Comment by IhateTrains** [comment]
> What version do u use, as i understand u use old version, which doesnt work with rc1, use rc1 version with rc1

This was indeed reported for a MessageBox.Avalonia version prior to RC1. Sorry for not closing the issue!
