### ISSUE TITLE
Bug - Copy text from dialog causes exception

### ISSUE THREAD

**Issue by alexandrehtrb** [AvaloniaCommunity/MessageBox.Avalonia#154]
I have a dialog with text on it. When I select and copy the text using Ctrl+C, an exception arises and the program crashes. For some reason, the exception does not happen if the text is copied using mouse right-click and then copy.

Dialog built and shown like this:

```cs
private void ShowHelpDialog()
{
    Bitmap bitmap = new(AssetLoader.Open(new("avares://Pororoca.Desktop/Assets/Images/pororoca.png")));

    var msgbox = MessageBoxManager.GetMessageBoxStandard(
        new MessageBoxStandardParams()
        {
            ContentTitle = "title",
            ContentMessage = "content",
            WindowStartupLocation = WindowStartupLocation.CenterScreen,
            WindowIcon = new(bitmap),
            ButtonDefinitions = ButtonEnum.Ok
        });
    Dispatcher.UIThread.Post(async () => await msgbox.ShowAsync());
}
```

Exception in console:

```
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at MsBox.Avalonia.Controls.MsBoxStandardView.Copy()
   at CompiledAvaloniaXaml.XamlIlTrampolines.MsBox.Avalonia:MsBox.Avalonia.ViewModels.AbstractMsBoxViewModel+Copy_0!CommandExecuteTrampoline(Object, Object)
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.CommandAccessorPlugin.CommandAccessor.Command.Execute(Object parameter)
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.X11.X11Window.DispatchInput(RawInputEventArgs args)
   at Avalonia.RawEventGrouper.Dispatch(RawInputEventArgs ev)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Pororoca.Desktop.Program.Main(String[] args) in /home/runner/work/Pororoca/Pororoca/src/Pororoca.Desktop/Program.cs:line 17
```

**Comment by CreateLab** [comment]
what version do u use?

**Comment by alexandrehtrb** [comment]
> what version do u use?

The latest

**Comment by CalvinWilkinson** [comment]
I am getting the same behavior as well.
